language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  hipchat:
    rooms:
      secure: Di57aLpGum5Fi0tLWGE+rHrtOxJQq92i/Nau3p5WJ8tP7ev1nOT9PM+q/XIygLXrWZvl5pH6VLbxk5yY7hjg+nZgHvZMHmYKbNKzQ9RxwsFDiNr3Rz01ANPT2S+DdcY8vP8RjsoS8BitnPELSPQvlgYCdoeQIUvkBs5HtoBNTvg=
